version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "16:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: handsontable
    versions:
    - "> 6.1.1"
  - dependency-name: copy-webpack-plugin
    versions:
    - 7.0.0
    - 8.1.0
  - dependency-name: urijs
    versions:
    - 1.19.6
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
- package-ecosystem: gomod
  directory: "/api"
  schedule:
    interval: daily
    time: "16:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: google.golang.org/api
    versions:
    - 0.37.0
    - 0.38.0
    - 0.39.0
    - 0.40.0
    - 0.41.0
    - 0.42.0
    - 0.43.0
    - 0.44.0
    - 0.45.0
  - dependency-name: cloud.google.com/go
    versions:
    - 0.75.0
    - 0.76.0
    - 0.77.0
    - 0.78.0
    - 0.79.0
    - 0.80.0
    - 0.81.0
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.37.19
    - 1.37.30
    - 1.37.31
    - 1.37.32
    - 1.37.33
    - 1.37.9
    - 1.38.11
    - 1.38.15
    - 1.38.16
    - 1.38.19
    - 1.38.20
    - 1.38.21
    - 1.38.22
    - 1.38.23
    - 1.38.24
    - 1.38.25
    - 1.38.26
    - 1.38.4
    - 1.38.6
  - dependency-name: github.com/go-openapi/swag
    versions:
    - 0.19.13
    - 0.19.14
  - dependency-name: github.com/go-openapi/strfmt
    versions:
    - 0.20.0
  - dependency-name: github.com/getsentry/sentry-go
    versions:
    - 0.9.0
  - dependency-name: github.com/go-openapi/validate
    versions:
    - 0.20.1
  - dependency-name: github.com/go-openapi/errors
    versions:
    - 0.19.9
